// <auto-generated />
using AnimeRU.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeRU.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeRU.Shared.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "https://flxt.tmsimg.com/assets/p13993632_b_v8_ab.jpg",
                            Name = "Attack On Titan - Episodul 1",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 2,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BM2RmZmI2NmUtNDhjMi00MGQ4LWIyYTEtZmMxM2E1ZjBkYTU0XkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg",
                            Name = "Domestic No Kanojo - Episodul 1",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 3,
                            ImageURL = "https://static.wikia.nocookie.net/tokyoghoul/images/9/9b/Season_two_blu-ray_box_cover.png/revision/latest?cb=20161204225315",
                            Name = "Tokyo Ghoul - Episodul 1",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 4,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BNjMxMDJkNGQtMDkwMy00ZmQyLThjNWQtODYyODU2MmYwYTA1XkEyXkFqcGdeQXVyMTQ3MjMyMTYz._V1_.jpg",
                            Name = "Kuroko no basket - Episodul 1",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 5,
                            ImageURL = "https://static.wikia.nocookie.net/jujutsu-kaisen/images/8/88/Anime_Key_Visual_2.png/revision/latest?cb=20201212034001",
                            Name = "Jujutsu Kaisen - Episodul 1",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 6,
                            ImageURL = "https://flxt.tmsimg.com/assets/p13993632_b_v8_ab.jpg",
                            Name = "Attack On Titan - Episodul 2",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 7,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BM2RmZmI2NmUtNDhjMi00MGQ4LWIyYTEtZmMxM2E1ZjBkYTU0XkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg",
                            Name = "Domestic No Kanojo - Episodul 2",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 8,
                            ImageURL = "https://static.wikia.nocookie.net/tokyoghoul/images/9/9b/Season_two_blu-ray_box_cover.png/revision/latest?cb=20161204225315",
                            Name = "Tokyo Ghoul - Episodul 2",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 9,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BNjMxMDJkNGQtMDkwMy00ZmQyLThjNWQtODYyODU2MmYwYTA1XkEyXkFqcGdeQXVyMTQ3MjMyMTYz._V1_.jpg",
                            Name = "Kuroko no basket - Episodul 2",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        },
                        new
                        {
                            Id = 10,
                            ImageURL = "https://static.wikia.nocookie.net/jujutsu-kaisen/images/8/88/Anime_Key_Visual_2.png/revision/latest?cb=20201212034001",
                            Name = "Jujutsu Kaisen - Episodul 2",
                            Video = "https://mega.nz/embed/ERYTUSwZ#CtpBVQBt66T8i4YX5bdnBxoeOGfQxXYZ1c6RTTlPLqg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
